development:
  adapter: postgresql
  encoding: unicode
  database: hearthstone_development
  pool: 5
  username: hearthstone
  password: Welcome1
test:
  adapter: postgresql
  encoding: unicode
  database: hearthstone_test
  pool: 5
  username: hearthstone
  password: Welcome1
production:
  adapter: postgresql
  encoding: unicode
  database: hearthstone_production
  pool: 5
  username: hearthstone
  password: Welcome1